import { execSync } from 'node:child_process';
import { rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { assertTestDatabaseUrl } from './assert-test-database-url';
import { seedTestData } from './seed-data';
import { startTestDatabase, stopTestDatabase } from './test-database';

/**
 * E2E test runner — starts the testcontainer and writes .env.development.local
 * BEFORE invoking Playwright, so Next.js sees the DATABASE_URL at startup.
 *
 * Playwright's globalSetup/globalTeardown are no-ops for DB setup —
 * this script handles the full lifecycle.
 */
const ENV_FILE = resolve(__dirname, '../../.env.development.local');

const run = async (): Promise<void> => {
  try {
    // Phase 1: Start testcontainer + write env file
    const databaseUrl = await startTestDatabase();
    assertTestDatabaseUrl(databaseUrl);

    writeFileSync(ENV_FILE, `# Auto-generated by E2E start-e2e.ts — delete if stale\nDATABASE_URL="${databaseUrl}"\n`);
    process.stdout.write(`[e2e] DATABASE_URL written to .env.development.local (${databaseUrl.split('@')[1]?.split('/')[0] ?? 'unknown'})\n`);

    await seedTestData(databaseUrl);

    // Phase 2: Run Playwright (it will read .env.development.local via Next.js)
    // Filter out '--' separators that pnpm injects
    const args = process.argv
      .slice(2)
      .filter((a) => a !== '--')
      .join(' ');
    execSync(`npx playwright test ${args}`, {
      stdio: 'inherit',
      cwd: resolve(__dirname, '../..'),
    });
  } finally {
    // Cleanup
    try {
      rmSync(ENV_FILE);
    } catch {
      /* ignore */
    }
    await stopTestDatabase();
  }
};

run().catch((error) => {
  process.stderr.write(`${error}\n`);
  // eslint-disable-next-line unicorn/no-process-exit
  process.exit(1);
});
