import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    projects: [
      'apps/web',
      'apps/orchestrator',
      'packages/ui',
      'packages/logger',
      'packages/plugin-contract',
      'packages/plugins/context',
      'packages/plugins/discord',
      'packages/plugins/web',
      'packages/plugins/delegation',
      'packages/plugins/activity',
      'packages/plugins/metrics',
      'packages/plugins/summarization',
      'packages/plugins/identity',
      'packages/plugins/auto-namer',
      'packages/plugins/audit',
      'packages/plugins/time',
      'packages/plugins/cron',
      'packages/plugins/project',
      'packages/plugins/playwright',
      'packages/plugins/tasks',
      'packages/plugins/music',
      'packages/plugins/search',
      'packages/plugins/storytelling',
      'packages/vector-search',
      'packages/database',
      'packages/oauth',
      'packages/plugins/validator',
      'packages/plugins/outlook',

      'packages/plugins/calendar',
      'packages/plugins/ssh',
      'packages/plugins/notifications',
      'packages/plugins/workspace',
    ],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json'],
      reportsDirectory: './coverage',
      exclude: [
        '**/*.config.ts',
        '**/*.d.ts',
        '**/*.test.ts',
        '**/*.test.tsx',
        '**/*.spec.ts',
        '**/*.spec.tsx',
        '**/prisma/generated/**',
        '**/.next/**',
        '**/node_modules/**',
        '**/dist/**',
        '**/coverage/**',
      ],
    },
  },
});
