// scripts/generate-plugin-registry.ts
import { writeFileSync } from 'node:fs';
import { dirname, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { glob } from 'glob';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

type FieldEntry = {
  name: string;
  type: string;
  label: string;
  description?: string;
  required?: boolean;
  secret?: boolean;
  default?: string | number | boolean;
  options?: Array<{ label: string; value: string }>;
};

type PluginEntry = {
  pluginName: string;
  fields: FieldEntry[];
};

type Main = () => Promise<void>;

const main: Main = async () => {
  const schemaFiles = await glob('packages/plugins/*/src/_helpers/settings-schema.ts', {
    cwd: ROOT,
    absolute: true,
  });

  console.log(`Found ${schemaFiles.length} settings schema file(s):`);

  const entries: PluginEntry[] = [];
  let failures = 0;

  for (const absolutePath of schemaFiles) {
    // Derive plugin name from path: …/packages/plugins/PLUGIN_NAME/src/_helpers/settings-schema.ts
    const parts = relative(ROOT, absolutePath).split(sep);
    const pluginName = parts[2];
    if (pluginName === undefined) {
      continue;
    }

    let mod: { settingsSchema?: { toFieldArray: () => FieldEntry[] } };
    try {
      mod = await import(absolutePath);
    } catch (err) {
      console.warn(`  Warning: ${pluginName}: failed to import — ${err instanceof Error ? err.message : String(err)}`);
      failures++;
      continue;
    }

    if (!mod.settingsSchema?.toFieldArray) {
      console.warn(`  Warning: ${pluginName}: no settingsSchema export, skipping`);
      failures++;
      continue;
    }

    const fields = mod.settingsSchema.toFieldArray();
    entries.push({ pluginName, fields });
    console.log(`  OK: ${pluginName}: ${fields.length} field(s)`);
  }

  if (failures > 0) {
    console.error(`\n${failures} schema file(s) failed to load`);
    process.exit(1);
  }

  const output = `// AUTO-GENERATED by scripts/generate-plugin-registry.ts — do not edit manually
// Re-run with: pnpm plugin:generate

export type PluginSettingsField = {
  name: string;
  type: string;
  label: string;
  description?: string;
  required?: boolean;
  secret?: boolean;
  default?: string | number | boolean;
  options?: Array<{ label: string; value: string }>;
};

export type PluginSettingsEntry = {
  pluginName: string;
  fields: PluginSettingsField[];
};

export const pluginSettingsRegistry: PluginSettingsEntry[] = ${JSON.stringify(entries, null, 2)};
`;

  const outputPath = resolve(ROOT, 'apps/web/src/generated/plugin-settings-registry.ts');
  writeFileSync(outputPath, output, 'utf-8');
  console.log(`\nWrote ${entries.length} plugin(s) to apps/web/src/generated/plugin-settings-registry.ts`);
};

main().catch((err) => {
  console.error('Generator failed:', err);
  process.exit(1);
});
